"""add user category weekly hours internal project

Revision ID: 003
Revises: 002
Create Date: 2024-07-12 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_internal', sa.Boolean(), nullable=True))
    op.execute("UPDATE projects SET is_internal = false")
    op.alter_column('projects', 'is_internal', nullable=False)

    user_category_enum = sa.Enum('pj', 'clt', 'estagiario', 'dono', name='usercategory')
    user_category_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('users', sa.Column('category', sa.Enum('pj', 'clt', 'estagiario', 'dono', name='usercategory'), nullable=True))
    op.execute("UPDATE users SET category = 'clt'")
    op.alter_column('users', 'category', nullable=False)

    op.add_column('users', sa.Column('weekly_hours', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weekly_hours')
    op.drop_column('users', 'category')
    op.drop_column('projects', 'is_internal')
    sa.Enum(name='usercategory').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###